### ISSUE TITLE
nstools version 0.2.5 not available

### ISSUE THREAD

**Issue by jumarko** [damn/Cyber-Dungeon-Quest#1]
I cloned the repo and tried to run the project via `lein dev`.
I'm getting the following error
```
Could not find artifact nstools:nstools:jar:0.2.5 in central (https://repo1.maven.org/maven2/)
Could not find artifact nstools:nstools:jar:0.2.5 in clojars (https://repo.clojars.org/)
Could not find artifact nstools:nstools:jar:0.2.5 in jitpack (https://jitpack.io)
```

As far as I can see, only version 0.2.4 is published: https://clojars.org/nstools
<img width="1373" alt="image" src="https://github.com/damn/Cyber-Dungeon-Quest/assets/1083629/f9a7b5cc-6946-444e-9b0e-438a46ea15a0">

**Comment by damn** [comment]
Fixed in c7de66c

Please try it again !
