### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by IMLaoJI** [damn/Cyber-Dungeon-Quest#2]
Hello, has the code not been updated for a long time? I cloned it and it cannot run. Is there something wrong with the gdl package?

**Comment by damn** [comment]
Im working on it a lot since a week, so it should run, there are only a few commits inbetween where it was broken.

Is there any error message ?

**Comment by IMLaoJI** [comment]
![image](https://github.com/damn/Cyber-Dungeon-Quest/assets/16029951/801cb061-4b8e-4d64-8305-493ea395bb7b)

![image](https://github.com/damn/Cyber-Dungeon-Quest/assets/16029951/1c67508f-86a0-4d04-8fc9-6766d6954edc)

In addition, I cant't downloaded [com.github.damn/gdl "main-SNAPSHOT"] through jetbrain idea. This dependency cannot be jumped normally in the code.

**Comment by IMLaoJI** [comment]
![image](https://github.com/damn/Cyber-Dungeon-Quest/assets/16029951/417890f9-2517-47a7-af9f-5d45c0094ae2)

I also reported this error when I started using lein dev alone.

**Comment by IMLaoJI** [comment]
![image](https://github.com/damn/Cyber-Dungeon-Quest/assets/16029951/d18c8b72-4011-4096-ab88-3721a1dc39b6)

In addition, I got some errors when cloning the project.

**Comment by damn** [comment]
Thanks for the input.

I fixed it by setting the gdl dependency to a fixed commit, it did not download the snapshot from jitpack.

Also I renamed the namespaces with question-marks.

Please try again!

**Comment by IMLaoJI** [comment]
It has been fixed now, but I started it through lein dev. Can I start repl through idea's cursive plug-in, and then debug and develop?

**Comment by damn** [comment]
I do not really know about that plugin, but I just renamed `app.start/app` to `app.start/-main`. It can be used without the gdl dev-loop now with plain `lein run -m app.start`.

**Comment by damn** [comment]
But then also not giving you a refresh-loop and a REPL, but I guess you can start your REPL in whatever way you want. But be aware that libgdx (at least on mac) requires the first thread for rendering and launching the application. So start your REPL before.

**Comment by IMLaoJI** [comment]
Okay, thank you for your repair and patient guidance. I have successfully set up the local environment
